import { Crop } from "@/types/crop";

/**
 * Static sample data used both for the seed script and as fallback
 * when Firebase is not configured.
 */
export const SAMPLE_CROPS: Omit<Crop, "id">[] = [
  {
    nameJa: "トマト",
    nameEn: "Tomato",
    scientificName: "Solanum lycopersicum",
    family: "ナス科",
    category: "fruit-vegetable",
    seasons: ["summer"],
    difficulty: 2,
    description:
      "日本で最も人気のある野菜のひとつ。真っ赤に熟したトマトはビタミンCやリコピンが豊富で、生食はもちろん、料理の万能食材として親しまれています。家庭菜園でも定番の品種です。",
    tips: [
      "支柱を立て、わき芽を取ることで実付きが良くなります",
      "水はけの良い土壌を好み、乾燥気味に管理するのがコツです",
      "実が割れる「裂果」を防ぐため、水やりは均一に行いましょう",
      "日当たりの良い場所に植えることが重要です",
    ],
    soilType: "水はけの良い弱酸性土壌（pH 6.0–6.5）",
    waterFrequency: "週2〜3回（土が乾いたら）",
    sunlight: "日当たり良好（1日6時間以上）",
    harvestPeriodDays: 70,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3, sowing: true },
      { month: 4, sowing: true, planting: true },
      { month: 5, planting: true },
      { month: 6 },
      { month: 7, harvesting: true },
      { month: 8, harvesting: true },
      { month: 9, harvesting: true },
      { month: 10 },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "ほうれん草",
    nameEn: "Spinach",
    scientificName: "Spinacia oleracea",
    family: "ヒユ科",
    category: "leaf-vegetable",
    seasons: ["spring", "autumn", "winter"],
    difficulty: 1,
    description:
      "鉄分や葉酸が豊富な緑黄色野菜。寒さに強く、秋から春にかけての栽培が得意です。ベビーリーフとしても利用でき、初心者でも育てやすい定番の葉物野菜です。",
    tips: [
      "酸性土壌を嫌うため、苦土石灰で中和してから植えましょう",
      "密植せず、間引きをしながら育てると葉が大きくなります",
      "寒い時期の方が甘みが増して美味しくなります",
      "夏の高温期は避け、秋まきか春まきが適しています",
    ],
    soilType: "中性〜弱アルカリ性土壌（pH 6.5–7.0）",
    waterFrequency: "週3〜4回（土が乾き始めたら）",
    sunlight: "半日陰でも可（ただし日当たりが良い方が育ちが良い）",
    harvestPeriodDays: 40,
    calendar: [
      { month: 1, harvesting: true },
      { month: 2, harvesting: true },
      { month: 3, sowing: true, harvesting: true },
      { month: 4, sowing: true, harvesting: true },
      { month: 5 },
      { month: 6 },
      { month: 7 },
      { month: 8 },
      { month: 9, sowing: true },
      { month: 10, sowing: true, harvesting: true },
      { month: 11, harvesting: true },
      { month: 12, harvesting: true },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "大根",
    nameEn: "Daikon Radish",
    scientificName: "Raphanus sativus var. longipinnatus",
    family: "アブラナ科",
    category: "root-vegetable",
    seasons: ["autumn", "winter"],
    difficulty: 1,
    description:
      "日本料理に欠かせない根菜。おでん、煮物、大根おろしと用途が広く、消化酵素（ジアスターゼ）を豊富に含みます。秋まきが主流で、初心者でも育てやすい野菜のひとつです。",
    tips: [
      "深くまで耕した土に直まきするのがポイントです",
      "間引きをしっかり行うことで太い大根が育ちます",
      "肩が土から出てきたら収穫のサインです",
      "連作障害が出やすいので、3〜4年は同じ場所を避けましょう",
    ],
    soilType: "深めに耕した水はけの良い砂壌土（pH 6.0–7.0）",
    waterFrequency: "週2〜3回",
    sunlight: "日当たり良好",
    harvestPeriodDays: 60,
    calendar: [
      { month: 1, harvesting: true },
      { month: 2, harvesting: true },
      { month: 3 },
      { month: 4 },
      { month: 5 },
      { month: 6 },
      { month: 7 },
      { month: 8, sowing: true },
      { month: 9, sowing: true },
      { month: 10, harvesting: true },
      { month: 11, harvesting: true },
      { month: 12, harvesting: true },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "キュウリ",
    nameEn: "Cucumber",
    scientificName: "Cucumis sativus",
    family: "ウリ科",
    category: "fruit-vegetable",
    seasons: ["summer"],
    difficulty: 2,
    description:
      "夏野菜の定番。水分が豊富でさっぱりとした風味が特徴です。生育旺盛で収穫量が多く、家庭菜園でも人気があります。ネットを張って上に誘引して育てます。",
    tips: [
      "ネットや支柱に誘引して立体栽培を心がけましょう",
      "収穫は早めに行い、株への負担を減らすのがコツです",
      "水分をよく欲しがるので、乾燥させないよう注意しましょう",
      "うどん粉病に注意し、風通しの良い環境を保ちましょう",
    ],
    soilType: "水はけが良く肥沃な土壌（pH 6.0–7.0）",
    waterFrequency: "毎日（乾燥に弱い）",
    sunlight: "日当たり良好",
    harvestPeriodDays: 55,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3 },
      { month: 4, sowing: true },
      { month: 5, sowing: true, planting: true },
      { month: 6, planting: true, harvesting: true },
      { month: 7, harvesting: true },
      { month: 8, harvesting: true },
      { month: 9 },
      { month: 10 },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "なす",
    nameEn: "Eggplant",
    scientificName: "Solanum melongena",
    family: "ナス科",
    category: "fruit-vegetable",
    seasons: ["summer"],
    difficulty: 3,
    description:
      "紫色の美しい果実が特徴の夏野菜。焼き茄子、麻婆茄子、天ぷらなど和洋中幅広い料理に活用できます。肥料を多く必要とする「肥料食い」として知られています。",
    tips: [
      "「一番果」は小さいうちに摘み取り、株を充実させましょう",
      "追肥（お礼肥え）をこまめに行うことが大切です",
      "夏の高温乾燥時には「更新剪定」で秋茄子を楽しめます",
      "カミキリムシやコナジラミに注意しましょう",
    ],
    soilType: "保水性・排水性のバランスが良い肥沃な土壌（pH 6.0–6.5）",
    waterFrequency: "毎日（特に真夏は朝晩）",
    sunlight: "日当たり良好",
    harvestPeriodDays: 80,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3, sowing: true },
      { month: 4, sowing: true },
      { month: 5, planting: true },
      { month: 6, planting: true },
      { month: 7, harvesting: true },
      { month: 8, harvesting: true },
      { month: 9, harvesting: true },
      { month: 10, harvesting: true },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "レタス",
    nameEn: "Lettuce",
    scientificName: "Lactuca sativa",
    family: "キク科",
    category: "leaf-vegetable",
    seasons: ["spring", "autumn"],
    difficulty: 2,
    description:
      "サラダに欠かせない葉野菜。春と秋が栽培適期で、高温に弱い性質があります。結球型・散葉型など多様な品種があり、ベランダでのプランター栽培にも向いています。",
    tips: [
      "高温期の栽培は避け、春まきか秋まきにしましょう",
      "表面が軽く乾いたら水やりするよう管理します",
      "光発芽種子のため、種まき後は覆土を薄くします",
      "アブラムシに注意し、防虫ネットの活用が効果的です",
    ],
    soilType: "水はけが良く適度に保水力のある土壌（pH 6.0–6.8）",
    waterFrequency: "週3〜4回",
    sunlight: "半日陰から日当たり良好",
    harvestPeriodDays: 50,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3, sowing: true },
      { month: 4, sowing: true, planting: true },
      { month: 5, planting: true, harvesting: true },
      { month: 6 },
      { month: 7 },
      { month: 8, sowing: true },
      { month: 9, sowing: true, planting: true },
      { month: 10, planting: true, harvesting: true },
      { month: 11, harvesting: true },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "いちご",
    nameEn: "Strawberry",
    scientificName: "Fragaria × ananassa",
    family: "バラ科",
    category: "fruit",
    seasons: ["spring"],
    difficulty: 3,
    description:
      "春を代表する果物。甘酸っぱい香りと味が魅力で、ビタミンCが豊富です。苗から育てるのが一般的で、ランナーを使った株の更新が必要です。家庭菜園でも人気の高い果物です。",
    tips: [
      "秋に苗を植え付け、翌春の収穫を目指す長期栽培です",
      "花が咲いたら人工授粉で実付きが良くなります",
      "ランナーを伸ばして子苗を取り、株を更新しましょう",
      "うどん粉病と灰色かび病に注意が必要です",
    ],
    soilType: "水はけの良い弱酸性土壌（pH 5.5–6.5）",
    waterFrequency: "週2〜3回（開花・結実期はこまめに）",
    sunlight: "日当たり良好",
    harvestPeriodDays: 180,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3, harvesting: true },
      { month: 4, harvesting: true },
      { month: 5, harvesting: true },
      { month: 6 },
      { month: 7 },
      { month: 8 },
      { month: 9, planting: true },
      { month: 10, planting: true },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "バジル",
    nameEn: "Basil",
    scientificName: "Ocimum basilicum",
    family: "シソ科",
    category: "herb",
    seasons: ["summer"],
    difficulty: 1,
    description:
      "イタリア料理に欠かせないハーブ。爽やかな香りが特徴で、トマトとの相性が抜群です。プランターでも育てやすく、ベランダハーブとして人気があります。",
    tips: [
      "摘心（ピンチ）を行い、葉の収量を増やしましょう",
      "花が咲くと葉が固くなるので、花穂は摘み取ります",
      "寒さに非常に弱く、気温が15℃以下になると枯れます",
      "トマトと一緒に植えると互いに良い影響を与え合います",
    ],
    soilType: "水はけの良い弱酸性土壌（pH 6.0–7.0）",
    waterFrequency: "週2〜3回（表面が乾いたら）",
    sunlight: "日当たり良好",
    harvestPeriodDays: 45,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3 },
      { month: 4, sowing: true },
      { month: 5, sowing: true, planting: true },
      { month: 6, planting: true, harvesting: true },
      { month: 7, harvesting: true },
      { month: 8, harvesting: true },
      { month: 9, harvesting: true },
      { month: 10 },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "じゃがいも",
    nameEn: "Potato",
    scientificName: "Solanum tuberosum",
    family: "ナス科",
    category: "root-vegetable",
    seasons: ["spring", "autumn"],
    difficulty: 2,
    description:
      "世界中で愛される根菜。炭水化物やビタミンCが豊富で、様々な料理に使えます。種イモから育てる独特の栽培方法が特徴的。春と秋の2作が楽しめます。",
    tips: [
      "種イモを切る場合は切り口を乾かしてから植えましょう",
      "芽が出てきたら土寄せをして緑化を防ぎます",
      "茎葉が黄色くなり始めたら収穫のサインです",
      "連作障害が強いので、4〜5年間隔をあけましょう",
    ],
    soilType: "水はけの良い弱酸性土壌（pH 5.0–6.0）",
    waterFrequency: "週2回程度",
    sunlight: "日当たり良好",
    harvestPeriodDays: 90,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3, planting: true },
      { month: 4, planting: true },
      { month: 5 },
      { month: 6, harvesting: true },
      { month: 7, harvesting: true },
      { month: 8, planting: true },
      { month: 9, planting: true },
      { month: 10 },
      { month: 11, harvesting: true },
      { month: 12, harvesting: true },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "ミニトマト",
    nameEn: "Cherry Tomato",
    scientificName: "Solanum lycopersicum var. cerasiforme",
    family: "ナス科",
    category: "fruit-vegetable",
    seasons: ["summer"],
    difficulty: 1,
    description:
      "トマトよりも育てやすく、家庭菜園入門にぴったりの品種。甘みが強く、子どもにも人気です。次々と実をつけるので、長期間収穫を楽しめます。",
    tips: [
      "わき芽取りは、一本仕立てか二本仕立てかを決めてから行いましょう",
      "房のトマトは下から上へと順番に色づきます",
      "鈴なりになったら果房ごと収穫できます",
      "雨に当たると実が割れやすいので、雨よけ栽培が効果的です",
    ],
    soilType: "水はけの良い弱酸性土壌（pH 6.0–6.5）",
    waterFrequency: "週2〜3回",
    sunlight: "日当たり良好",
    harvestPeriodDays: 65,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3, sowing: true },
      { month: 4, sowing: true, planting: true },
      { month: 5, planting: true },
      { month: 6, harvesting: true },
      { month: 7, harvesting: true },
      { month: 8, harvesting: true },
      { month: 9, harvesting: true },
      { month: 10 },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "ブロッコリー",
    nameEn: "Broccoli",
    scientificName: "Brassica oleracea var. italica",
    family: "アブラナ科",
    category: "leaf-vegetable",
    seasons: ["autumn", "winter"],
    difficulty: 2,
    description:
      "栄養価の高い緑黄色野菜。ビタミンC・K、食物繊維が豊富です。中央の花蕾を収穫した後も、側花蕾が次々と出てくるので長期間楽しめます。",
    tips: [
      "頂花蕾がしっかり締まっているうちに収穫しましょう",
      "黄色くなった花蕾は苦くなるので早めに収穫します",
      "青虫や アオムシに注意し、防虫ネットが効果的です",
      "側枝から出る脇花蕾も美味しく食べられます",
    ],
    soilType: "水はけが良く有機質豊富な土壌（pH 6.0–7.0）",
    waterFrequency: "週2〜3回",
    sunlight: "日当たり良好",
    harvestPeriodDays: 90,
    calendar: [
      { month: 1, harvesting: true },
      { month: 2, harvesting: true },
      { month: 3 },
      { month: 4 },
      { month: 5 },
      { month: 6 },
      { month: 7, sowing: true },
      { month: 8, sowing: true, planting: true },
      { month: 9, planting: true },
      { month: 10 },
      { month: 11, harvesting: true },
      { month: 12, harvesting: true },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
  {
    nameJa: "枝豆",
    nameEn: "Edamame",
    scientificName: "Glycine max",
    family: "マメ科",
    category: "grain",
    seasons: ["summer"],
    difficulty: 2,
    description:
      "夏のビールのお供として日本人に愛される野菜。大豆を未熟なうちに収穫したもの。タンパク質・ビタミンB1が豊富で、根粒菌が土壌を豊かにする効果もあります。",
    tips: [
      "さやの中の豆がふっくらしてきたら収穫適期です",
      "収穫後は鮮度が落ちるため、すぐに茹でるのがポイントです",
      "害虫（カメムシ、マメシンクイガ）に注意しましょう",
      "後作にキャベツや白菜を植えると連作障害を防げます",
    ],
    soilType: "水はけが良く有機質豊富な土壌（pH 6.0–6.5）",
    waterFrequency: "週2〜3回（開花・結実期は毎日）",
    sunlight: "日当たり良好",
    harvestPeriodDays: 75,
    calendar: [
      { month: 1 },
      { month: 2 },
      { month: 3 },
      { month: 4, sowing: true },
      { month: 5, sowing: true },
      { month: 6 },
      { month: 7, harvesting: true },
      { month: 8, harvesting: true },
      { month: 9 },
      { month: 10 },
      { month: 11 },
      { month: 12 },
    ],
    imageUrl: "",
    thumbnailUrl: "",
  },
];
